[package]
name = "newtlf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["staticlib", "lib"]

[dependencies]
nom="7.1"
cstr = "0.2"
libc = "0.2"
thiserror = "1.0.37"
linereader="0.4"

[build-dependencies]
cbindgen = "0.25"

