[package]
name = "rustlf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["staticlib"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
bbqueue = "0.5.1"
thiserror = "1.0.37"
tlf = { path = "tlf-sys" }

[build-dependencies]
cbindgen = "0.24.3"
