[package]
name = "rustlf"
version = "0.1.0"
edition = "2021"

[lib]
crate-type=["staticlib"]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]

[build-dependencies]
bindgen = "0.63"
cbindgen = "0.24"
pkg-config = "0.3"
